#!/usr/bin/env node
/*
 * build.js — assemble index.html from src/.
 *
 * The app ships as one self-contained index.html, so the service worker caches
 * a single shell and the app opens on a course with no signal. It is authored
 * as readable files under src/:
 *
 *   src/index.html   the markup, with an empty <style data-src="css"> and
 *                    <script data-src="js/..."> element where each block goes
 *   src/css/         the stylesheet, in cascade order
 *   src/js/boot/     the Firebase loader (runs first, before the app)
 *   src/js/app/      the app itself, in load order
 *   src/js/cloud/    sign-in, sync and live rounds
 *
 * Each placeholder is filled with its folder's files concatenated in filename
 * order -- the numeric prefixes are the load order, so a file is never moved
 * without renaming it. Nothing is transformed: the shipped code is the source.
 * The one generated piece is the course list, inlined from data/courses.json.
 *
 * No dependencies, so `npm test` can run the --check with nothing installed.
 *
 * Usage:
 *   node scripts/build.js          # write index.html
 *   node scripts/build.js --check  # fail if index.html is out of date (CI)
 */
"use strict";
const fs = require("fs");
const path = require("path");
const { validate, buildBlock } = require("./build-courses");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");
const OUT = path.join(ROOT, "index.html");
const DATA = path.join(ROOT, "data", "courses.json");
const COURSE_DB = "/*@build course-db*/";
const GENERATED =
  "<!-- Generated by scripts/build.js from src/ and data/courses.json. Do not edit this file:\n" +
  "     edit src/, then run `npm run build` and commit both. -->";

function fail(msg) {
  console.error("build: " + msg);
  process.exit(1);
}

function folder(rel) {
  const dir = path.join(SRC, rel);
  if (!fs.existsSync(dir)) fail(`src/${rel} does not exist`);
  const ext = rel === "css" ? ".css" : ".js";
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(ext)).sort();
  if (!files.length) fail(`src/${rel} has no ${ext} files`);
  return files.map((f) => fs.readFileSync(path.join(dir, f), "utf8")).join("");
}

function build() {
  const courses = JSON.parse(fs.readFileSync(DATA, "utf8"));
  validate(courses);
  let used = 0;
  let html = fs
    .readFileSync(path.join(SRC, "index.html"), "utf8")
    .replace(/<(style|script) data-src="([^"]+)"><\/\1>/g, (_, tag, rel) => {
      used++;
      return `<${tag}>\n${folder(rel)}</${tag}>`;
    });
  if (used !== 4) fail(`expected 4 data-src blocks in src/index.html, found ${used}`);
  if (html.split(COURSE_DB).length !== 2) fail(`expected one ${COURSE_DB} marker`);
  html = html.replace(COURSE_DB, () => buildBlock(courses));
  // Say so in the output, where someone about to edit it will look.
  const charset = '<meta charset="UTF-8">';
  if (!html.includes(charset)) fail("no charset meta in src/index.html");
  html = html.replace(charset, () => charset + GENERATED);
  return { html, courses };
}

function main(argv = process.argv) {
  const { html, courses } = build();
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (argv.includes("--check")) {
    if (html !== current) fail("index.html is out of date with src/ or data/courses.json -- run `npm run build`");
    console.log(`build: index.html is up to date (${courses.length} courses)`);
    return;
  }
  if (html === current) return console.log("build: no change");
  fs.writeFileSync(OUT, html);
  console.log(`build: wrote index.html (${(Buffer.byteLength(html) / 1024).toFixed(0)}KB, ${courses.length} courses)`);
}

if (require.main === module) main();
module.exports = { build, main };
